export const LABELS = {
	en: {
		addToCart: "Add to Cart",
		addBookToCart: "added to cart!",
		browseBooks: "Browse Books",
		cartEmpty: "Your cart is empty.",
		checkout: "Proceed to Checkout",
		checkoutMessage: "Thank you for your purchase!",
		clearCart: "Clear Cart",
		contactMessage: "Thank you for your message. We'll be in touch soon!",
		continueShopping: "Continue Shopping",
		coverOf: "Cover of",
		free: "Free",
		genre: "Genre",
		items: "Item(s)",
		orderSummary: "Order Summary",
		price: "Price",
		quantity: "Quantity",
		remove: "Remove",
		shipping: "Shipping",
		shoppingCart: "Shopping Cart",
		subtotal: "Subtotal",
		total: "Total",
		viewDetails: "View Details",
	},
	fr: {
		addToCart: "Ajouter au panier",
		addBookToCart: "ajouté au panier !",
		browseBooks: "Parcourir les livres",
		cartEmpty: "Votre panier est vide.",
		checkout: "Passer à la caisse",
		checkoutMessage: "Merci pour votre achat !",
		clearCart: "Vider le panier",
		contactMessage:
			"Merci pour votre message. Nous vous contacterons bientôt !",
		continueShopping: "Continuer vos achats",
		coverOf: "Couverture de",
		free: "Gratuite",
		genre: "Genre",
		items: "Article(s)",
		orderSummary: "Résumé de la commande",
		price: "Prix",
		quantity: "Quantité",
		remove: "Retirer",
		shipping: "Livraison",
		shoppingCart: "Panier",
		subtotal: "Sous-total",
		total: "Total",
		viewDetails: "Voir les détails",
	},
};
