export const LABELS = {
	en: {
		addToCart: "Add to Cart",
		browseBooks: "Browse Books",
		cartEmpty: "Your cart is empty.",
		checkout: "Proceed to Checkout",
		clearCart: "Clear Cart",
		continueShopping: "Continue Shopping",
		coverOf: "Cover of",
		free: "Free",
		genre: "Genre",
		items: "Item(s)",
		orderSummary: "Order Summary",
		price: "Price",
		quantity: "Quantity",
		remove: "Remove",
		shipping: "Shipping",
		shoppingCart: "Shopping Cart",
		subtotal: "Subtotal",
		total: "Total",
		viewDetails: "View Details",
	},
	fr: {
		addToCart: "Ajouter au panier",
		browseBooks: "Parcourir les livres",
		cartEmpty: "Votre panier est vide.",
		checkout: "Passer à la caisse",
		clearCart: "Vider le panier",
		continueShopping: "Continuer vos achats",
		coverOf: "Couverture de",
		free: "Gratuite",
		genre: "Genre",
		items: "Article(s)",
		orderSummary: "Résumé de la commande",
		price: "Prix",
		quantity: "Quantité",
		remove: "Retirer",
		shipping: "Livraison",
		shoppingCart: "Panier",
		subtotal: "Sous-total",
		total: "Total",
		viewDetails: "Voir les détails",
	},
};
